# TappsMCP Repository Ruleset Setup Script (PowerShell)
# Generated by TappsMCP tapps_init
#
# Prerequisites:
#   - gh CLI installed and authenticated
#   - Admin access to the repository
#
# Usage:
#   .\setup-rulesets.ps1

$ErrorActionPreference = "Stop"

$Repo = gh repo view --json nameWithOwner -q '.nameWithOwner'
Write-Output "Configuring rulesets for: $Repo"

$RulesJson = @'
{
  "name": "Main Branch Protection",
  "target": "branch",
  "enforcement": "active",
  "conditions": {
    "ref_name": {
      "include": ["refs/heads/main", "refs/heads/master"],
      "exclude": []
    }
  },
  "rules": [
    {
      "type": "pull_request",
      "parameters": {
        "required_approving_review_count": 1,
        "dismiss_stale_reviews_on_push": true,
        "require_last_push_approval": false,
        "required_review_thread_resolution": true
      }
    },
    {
      "type": "required_status_checks",
      "parameters": {
        "strict_required_status_checks_policy": true,
        "required_status_checks": [
          {
            "context": "TappsMCP Quality Gate"
          }
        ]
      }
    },
    {
      "type": "required_linear_history"
    }
  ]
}
'@

$RulesJson | gh api --method POST "repos/$Repo/rulesets" --input -

Write-Output "Ruleset created successfully."
Write-Output ""
Write-Output "Next steps:"
Write-Output "  1. Verify at: https://github.com/$Repo/settings/rules"
Write-Output "  2. Adjust required reviewers count as needed"
Write-Output "  3. Add additional status checks if you have other CI jobs"
