#!/usr/bin/env bash
# TappsMCP Repository Ruleset Setup Script
# Generated by TappsMCP tapps_init
#
# This script uses the GitHub CLI (gh) to configure repository rulesets.
# Rulesets replaced branch protection rules as the modern standard (GA 2025).
#
# Prerequisites:
#   - gh CLI installed and authenticated
#   - Admin access to the repository
#
# Usage:
#   chmod +x .github/scripts/setup-rulesets.sh
#   .github/scripts/setup-rulesets.sh

set -euo pipefail

REPO=$(gh repo view --json nameWithOwner -q '.nameWithOwner')
echo "Configuring rulesets for: $REPO"

# Create main branch protection ruleset
echo "Creating main branch protection ruleset..."
gh api \
  --method POST \
  "repos/$REPO/rulesets" \
  -f name="Main Branch Protection" \
  -f target=branch \
  -f enforcement=active \
  --input - <<'RULES_JSON'
{
  "conditions": {
    "ref_name": {
      "include": ["refs/heads/main", "refs/heads/master"],
      "exclude": []
    }
  },
  "rules": [
    {
      "type": "pull_request",
      "parameters": {
        "required_approving_review_count": 1,
        "dismiss_stale_reviews_on_push": true,
        "require_last_push_approval": false,
        "required_review_thread_resolution": true
      }
    },
    {
      "type": "required_status_checks",
      "parameters": {
        "strict_required_status_checks_policy": true,
        "required_status_checks": [
          {
            "context": "TappsMCP Quality Gate"
          }
        ]
      }
    },
    {
      "type": "required_linear_history"
    }
  ]
}
RULES_JSON

echo "Ruleset created successfully."
echo ""
echo "Next steps:"
echo "  1. Verify at: https://github.com/$REPO/settings/rules"
echo "  2. Adjust required reviewers count as needed"
echo "  3. Add additional status checks if you have other CI jobs"
